accessories_light_commands = {
    "an": True,
    "aktiviert": True,
    "aktiviere": True,
    "aktivieren": True,
    "ein": True,
    "einschalten": True,
    "schalte ein": True,
    "schalte dich ein": True,
    "schalte an": True,
    "schalte dich an": True,
    "gehe an": True,

    "aus": False,
    "deaktiviert": False,
    "deaktiviere": False,
    "deaktivieren": False,
    "ausschalten": False,
    "schalte aus": False,
    "schalte dich aus": False,
    "schalte ab": False,
    "schalte dich ab": False,
    "gehe aus": False,
}

accessories_general_turnouts_commands = {
    #Weichen Gerade/Grün
    "gerade": True,
    "schalte gerade": True,
    "schalte dich gerade": True,
    "schalte in die gerade position": True,
    "schalte in die position gerade": True,
    "schalte auf gerade": True,
    "schalte auf gerade um": True,
    "schalte dich auf gerade": True,
    "schalte dich auf gerade um": True,
    "setze auf gerade": True,
    "stelle auf gerade": True,
    "aktiviere gerade position": True,
    "wähle gerade aus": True,
    "lege auf gerade": True,
    "lege auf gerade um": True,
    "ändere auf gerade": True,
    "geradeaus": True,
    "geradeaus setzen": True,
    "schalte geradeaus": True,
    "nach geradeaus": True,
    "nach geradeaus schalten": True,

    "grün": True,
    "schalte grün": True,
    "schalte nach grün": True,
    "schalte dich grün": True,
    "schalte dich auf grün": True,
    "schalte dich auf grün um": True,
    "schalte in die grün position": True,
    "schalte in die position grün": True,
    "schalte auf grün": True,
    "schalte auf grün um": True,
    "setze auf grün": True,
    "stelle auf grün": True,
    "aktiviere grün position": True,
    "wähle grün aus": True,
    "lege auf grün": True,
    "lege auf grün um": True,
    "ändere auf grün": True,
    "auf grün setzen": True,
    "auf grün schalten": True,
    "auf grün stellen": True,

    # Weichen Rot/kurve/Abzweigend
    "kurve": False,
    "schalte kurve": False,
    "schalte die kurve": False,
    "schalte auf kurve": False,
    "schalte auf eine kurve": False,
    "schalte auf die kurve um": False,
    "schalte auf eine kurve um": False,
    "setze auf kurve": False,
    "stelle auf kurve": False,
    "aktiviere kurven position": False,
    "wähle kurve aus": False,
    "lege auf kurve": False,
    "ändere in kurve": False,
    "in kurve ändern": False,
    "in kurve schalten": False,
    "in kurve umschalten": False,
    "in eine kurve ändern": False,

    "abzweigend": False,
    "schalte abzweigend": False,
    "schalte abzweigend um": False,
    "schalte auf abzweigend": False,
    "schalte auf die abzweigend position": False,
    "setze auf abzweigend": False,
    "stelle auf abzweigend": False,
    "aktiviere abzweigend position": False,
    "wähle abzweigend aus": False,
    "lege auf abzweigend": False,
    "ändere auf abzweigend": False,

    "rot": False,
    "schalte rot": False,
    "schalte nach rot": False,
    "schalte dich rot": False,
    "schalte dich auf rot": False,
    "schalte dich auf rot um": False,
    "schalte in die rot position": False,
    "schalte in die position rot": False,
    "schalte auf rot": False,
    "schalte auf rot um": False,
    "setze auf rot": False,
    "stelle auf rot": False,
    "aktiviere rot position": False,
    "wähle rot aus": False,
    "lege auf rot ": False,
    "lege auf rot um": False,
    "ändere auf rot": False,
    "auf rot setzen": True,
    "auf rot schalten": True,
    "auf rot stellen": True,
}

accessories_right_turnouts_commands = {
    "rechts": False,
    "schalte rechts": False,
    "schalte nach rechts": False,
    "schalte dich rechts": False,
    "schalte dich auf rechts": False,
    "schalte dich nach rechts": False,
    "schalte dich auf rechts um": False,
    "schalte in die rechts position": False,
    "schalte in die rechte position": False,
    "schalte auf rechts": False,
    "schalte auf rechts um": False,
    "setze auf rechts": False,
    "stelle auf rechts": False,
    "aktiviere rechte position": False,
    "wähle rechts aus": False,
    "lege auf rechts": False,
    "lege auf rechts um": False,
    "ändere auf rechts": False,
    "nach rechts": False,
    "nach rechts schalten": False,
    "nach rechts stellen": False,
    "nach rechts umschalten": False,
    "nach rechts umstellen": False,
    "auf rechts": False,
    "auf rechts schalten": False,
    "auf rechts stellen": False,
    "auf rechts umschalten": False,
    "auf rechts umstellen": False,
    "auf die rechte position setzen": False,
    "auf die rechte position schalten": False,

    "links": True,
    "schalte links": True,
    "schalte nach links": True,
    "schalte dich links": True,
    "schalte dich auf links": True,
    "schalte dich nach links": True,
    "schalte dich auf links um": True,
    "schalte in die links position": True,
    "schalte in die linke position": True,
    "schalte auf links": True,
    "schalte auf links um": True,
    "setze auf links": True,
    "stelle auf links": True,
    "aktiviere linke position": True,
    "wähle links aus": True,
    "lege auf links": True,
    "lege auf links um": True,
    "ändere auf links": True,
    "nach links": True,
    "nach links schalten": True,
    "nach links stellen": True,
    "nach links umschalten": True,
    "nach links umstellen": True,
    "auf links": True,
    "auf links schalten": True,
    "auf links stellen": True,
    "auf links umschalten": True,
    "auf links umstellen": True,
    "auf die linke position setzen": True,
    "auf die linke position schalten": True,

}

accessories_left_turnouts_commands = {
    "rechts": True,
    "schalte rechts": True,
    "schalte dich rechts": True,
    "schalte dich auf rechts": True,
    "schalte dich nach rechts": True,
    "schalte dich auf rechts um": True,
    "schalte in die rechts position": True,
    "schalte in die rechte position": True,
    "schalte nach rechts": True,
    "schalte auf rechts": True,
    "schalte auf rechts um": True,
    "setze auf rechts": True,
    "stelle auf rechts": True,
    "aktiviere rechte position": True,
    "wähle rechts aus": True,
    "lege auf rechts": True,
    "lege auf rechts um": True,
    "ändere auf rechts": True,
    "nach rechts": True,
    "nach rechts schalten": True,
    "nach rechts stellen": True,
    "nach rechts umschalten": True,
    "nach rechts umstellen": True,
    "auf rechts": True,
    "auf rechts schalten": True,
    "auf rechts stellen": True,
    "auf rechts umschalten": True,
    "auf rechts umstellen": True,
    "auf die rechte position setzen": True,
    "auf die rechte position schalten": True,

    "links": False,
    "schalte links": False,
    "schalte nach links": False,
    "schalte dich links": False,
    "schalte dich auf links": False,
    "schalte dich nach links": False,
    "schalte dich auf links um": False,
    "schalte in die links position": False,
    "schalte in die linke position": False,
    "schalte auf links": False,
    "schalte auf links um": False,
    "setze auf links": False,
    "stelle auf links": False,
    "aktiviere linke position": False,
    "wähle links aus": False,
    "lege auf links": False,
    "lege auf links um": False,
    "ändere auf links": False,
    "nach links schalten": False,
    "nach links stellen": False,
    "nach links umschalten": False,
    "nach links umstellen": False,
    "auf links": False,
    "auf links schalten": False,
    "auf links stellen": False,
    "auf links umschalten": False,
    "auf links umstellen": False,
    "auf die linke position setzen": False,
    "auf die linke position schalten": False,
}

accessories_three_way_turnouts_commands = {
    # Weichen Links
    "links": "Links",
    "schalte links": "Links",
    "schalte nach links": "Links",
    "schalte dich links": "Links",
    "schalte dich auf links": "Links",
    "schalte dich nach links": "Links",
    "schalte dich auf links um": "Links",
    "schalte in die links position": "Links",
    "schalte in die linke position": "Links",
    "schalte auf links": "Links",
    "schalte auf links um": "Links",
    "setze auf links": "Links",
    "stelle auf links": "Links",
    "aktiviere linke position": "Links",
    "wähle links aus": "Links",
    "lege auf links": "Links",
    "lege auf links um": "Links",
    "ändere auf links": "Links",
    "nach links": "Links",
    "nach links schalten": "Links",
    "nach links stellen": "Links",
    "nach links umschalten": "Links",
    "nach links umstellen": "Links",
    "auf links": "Links",
    "auf links schalten": "Links",
    "auf links stellen": "Links",
    "auf links umschalten": "Links",
    "auf links umstellen": "Links",
    "auf die linke position setzen": "Links",
    "auf die linke position schalten": "Links",

    # Weichen Rechts
    "rechts": "Rechts",
    "schalte rechts": "Rechts",
    "schalte nach rechts": "Rechts",
    "schalte dich rechts": "Rechts",
    "schalte dich auf rechts": "Rechts",
    "schalte dich nach rechts": "Rechts",
    "schalte dich auf rechts um": "Rechts",
    "schalte in die rechts position": "Rechts",
    "schalte in die rechte position": "Rechts",
    "schalte auf rechts": "Rechts",
    "schalte auf rechts um": "Rechts",
    "setze auf rechts": "Rechts",
    "stelle auf rechts": "Rechts",
    "aktiviere rechte position": "Rechts",
    "wähle rechts aus": "Rechts",
    "lege auf rechts": "Rechts",
    "lege auf rechts um": "Rechts",
    "ändere auf rechts": "Rechts",
    "nach rechts": "Rechts",
    "nach rechts schalten": "Rechts",
    "nach rechts stellen": "Rechts",
    "nach rechts umschalten": "Rechts",
    "nach rechts umstellen": "Rechts",
    "auf rechts": "Rechts",
    "auf rechts schalten": "Rechts",
    "auf rechts stellen": "Rechts",
    "auf rechts umschalten": "Rechts",
    "auf rechts umstellen": "Rechts",
    "auf die rechte position setzen": "Rechts",
    "auf die rechte position schalten": "Rechts",
    "rechte position aktivieren": "Rechts",
    "rechte position wählen": "Rechts",

    # Weichen Mitte
    "mitte": "Mitte",
    "schalte mitte": "Mitte",
    "schalte nach mitte": "Mitte",
    "schalte dich in die mitte": "Mitte",
    "schalte in die mitte": "Mitte",
    "schalte dich auf mitte": "Mitte",
    "schalte dich auf die mitte": "Mitte",
    "schalte dich nach mitte": "Mitte",
    "schalte dich auf mitte um": "Mitte",
    "schalte in die mittlere position": "Mitte",
    "schalte auf mitte": "Mitte",
    "schalte auf mitte um": "Mitte",
    "setze auf mitte": "Mitte",
    "stelle auf mitte": "Mitte",
    "aktiviere mittlere position": "Mitte",
    "wähle mitte aus": "Mitte",
    "lege auf mitte": "Mitte",
    "lege auf mitte um": "Mitte",
    "ändere auf mitte": "Mitte",
    "nach mitte schalten": "Mitte",
    "nach mitte stellen": "Mitte",
    "nach mitte umschalten": "Mitte",
    "nach mitte umstellen": "Mitte",
    "auf mitte": "Mitte",
    "auf mitte schalten": "Mitte",
    "auf mitte stellen": "Mitte",
    "auf mitte umschalten": "Mitte",
    "auf mitte umstellen": "Mitte",
    "auf die mittlere position setzen": "Mitte",
    "auf die mittlere position schalten": "Mitte",
    "mittlere position aktivieren": "Mitte",
    "mittlere position wählen": "Mitte",
    "gerade": "Mitte",
    "schalte gerade": "Mitte",
    "schalte dich in die gerade": "Mitte",
    "schalte dich auf gerade": "Mitte",
    "schalte dich nach gerade": "Mitte",
    "schalte dich auf gerade um": "Mitte",
    "schalte in die gerade position": "Mitte",
    "schalte in die geradeaus position": "Mitte",
    "schalte auf gerade": "Mitte",
    "schalte auf gerade um": "Mitte",
    "setze auf gerade": "Mitte",
    "stelle auf gerade": "Mitte",
    "aktiviere gerade position": "Mitte",
    "wähle gerade aus": "Mitte",
    "lege auf gerade": "Mitte",
    "lege auf gerade um": "Mitte",
    "ändere auf gerade": "Mitte",
    "nach gerade schalten": "Mitte",
    "nach gerade stellen": "Mitte",
    "nach gerade umschalten": "Mitte",
    "nach gerade umstellen": "Mitte",
    "auf gerade": "Mitte",
    "auf gerade schalten": "Mitte",
    "auf gerade stellen": "Mitte",
    "auf gerade umschalten": "Mitte",
    "auf gerade umstellen": "Mitte",
    "auf die gerade position setzen": "Mitte",
    "auf die gerade position schalten": "Mitte",
    "gerade position aktivieren": "Mitte",
    "gerade position wählen": "Mitte",
    "geradeaus": "Mitte",
    "schalte geradeaus": "Mitte",
    "schalte dich in die richtung geradeaus": "Mitte",
    "schalte dich auf geradeaus": "Mitte",
    "schalte dich nach geradeaus": "Mitte",
    "schalte dich auf geradeaus um": "Mitte",
    "schalte auf geradeaus": "Mitte",
    "schalte auf geradeaus um": "Mitte",
    "setze auf geradeaus": "Mitte",
    "stelle auf geradeaus": "Mitte",
    "aktiviere geradeaus position": "Mitte",
    "wähle geradeaus aus": "Mitte",
    "lege auf geradeaus": "Mitte",
    "lege auf geradeaus um": "Mitte",
    "ändere auf geradeaus": "Mitte",
    "nach geradeaus schalten": "Mitte",
    "nach geradeaus stellen": "Mitte",
    "nach geradeaus umschalten": "Mitte",
    "nach geradeaus umstellen": "Mitte",
    "auf geradeaus": "Mitte",
    "auf geradeaus schalten": "Mitte",
    "auf geradeaus stellen": "Mitte",
    "auf geradeaus umschalten": "Mitte",
    "auf geradeaus umstellen": "Mitte",
    "auf die geradeaus position setzen": "Mitte",
    "auf die geradeaus position schalten": "Mitte",
    "geradeaus position aktivieren": "Mitte",
    "geradeaus position wählen": "Mitte",
    "in die mitte": "Mitte",
    "in die mitte schalten": "Mitte",
    "in die mitte stellen": "Mitte",
}

accessories_uncoupling_tracks_commands = {
    "aktivier": True,
    "aktiviere": True,
    "aktivieren": True,
    "aktiviert": True,
    "schalte ein": True,
    "schalte dich ein": True,
    "schalte an": True,
    "schalte dich an": True,
    "gehe an": True,
    "schalte auf": True,
    "entkuppeln": True,
    "entkupple": True,
    "abkuppeln": True,
    "entkupple dich": True,
    "löse verbindung": True,
    "löse die verbindung": True,
    "löse die kupplung": True,
    "löse die verbindung zwischen wagen": True,
    "trenne wagen": True,
    "trenne die wagen": True,
    "trenne den wagen": True,
    "trenne die anhänger": True,
    "trenne den anhänger": True,
    "löse die wagen": True,
    "löse den zug": True,
    "löse den zugteil": True,
    "löse die lokomotive": True,
    "kuppel ab": True,
    "kuppel die wagen ab": True,
    "kuppel die lokomotive ab": True,
    "kuppel den zugteil ab": True,
    "kuppel den zug ab": True,
    "kuppel dich ab": True,
    "kuppel die kupplung ab": True,
    "trenne die kupplung": True,
    "löse die verbindung zwischen lokomotive und wagen": True,
}