accessories_light_commands = {
    "an": True,
    "aktiviert": True,
    "aktiviere": True,
    "aktivieren": True,
    "ein": True,
    "einschalten": True,
    "schalte ein": True,
    "schalte dich ein": True,
    "schalte an": True,
    "schalte dich an": True,
    "gehe an": True,

    "aus": False,
    "deaktiviert": False,
    "deaktiviere": False,
    "deaktivieren": False,
    "ausschalten": False,
    "schalte aus": False,
    "schalte dich aus": False,
    "schalte ab": False,
    "schalte dich ab": False,
    "gehe aus": False,
}

accessories_general_turnouts_commands = {
    #Weichen Gerade/Grün
    "gerade": True,
    "schalte gerade": True,
    "schalte dich gerade": True,
    "schalte in die gerade position": True,
    "schalte in die position gerade": True,
    "schalte auf gerade": True,
    "schalte auf gerade um": True,
    "schalte dich auf gerade": True,
    "schalte dich auf gerade um": True,
    "setze auf gerade": True,
    "stelle auf gerade": True,
    "aktiviere gerade position": True,
    "wähle gerade aus": True,
    "lege auf gerade": True,
    "lege auf gerade um": True,
    "ändere auf gerade": True,

    "grün": True,
    "schalte grün": True,
    "schalte dich grün": True,
    "schalte dich auf grün": True,
    "schalte dich auf grün um": True,
    "schalte in die grün position": True,
    "schalte in die position grün": True,
    "schalte auf grün": True,
    "schalte auf grün um": True,
    "setze auf grün": True,
    "stelle auf grün": True,
    "aktiviere grün position": True,
    "wähle grün aus": True,
    "lege auf grün": True,
    "lege auf grün um": True,
    "ändere auf grün": True,

    # Weichen Rot/Kurve/Abzweigend
    "kurve": False,
    "schalte kurve": False,
    "schalte die Kurve": False,
    "schalte auf Kurve": False,
    "schalte auf die Kurve um": False,
    "setze auf Kurve": False,
    "stelle auf Kurve": False,
    "aktiviere Kurve-Position": False,
    "wähle Kurve aus": False,
    "lege auf Kurve": False,
    "ändere auf Kurve": False,

    "abzweigend": False,
    "schalte abzweigend": False,
    "schalte abzweigend um": False,
    "schalte auf abzweigend": False,
    "schalte auf die Abzweigend-Position": False,
    "setze auf abzweigend": False,
    "stelle auf abzweigend": False,
    "aktiviere Abzweigend-Position": False,
    "wähle Abzweigend aus": False,
    "lege auf abzweigend": False,
    "ändere auf abzweigend": False,

    "rot": False,
    "schalte rot": False,
    "schalte dich rot": False,
    "schalte dich auf rot": False,
    "schalte dich auf rot um": False,
    "schalte in die rot position": False,
    "schalte in die position rot": False,
    "schalte auf rot": False,
    "schalte auf rot um": False,
    "setze auf rot": False,
    "stelle auf rot": False,
    "aktiviere rot position": False,
    "wähle rot aus": False,
    "lege auf rot ": False,
    "lege auf rot um": False,
    "ändere auf rot": False,
}

accessories_right_turnouts_commands = {
    "rechts": False,
    "schalte rechts": False,
    "schalte dich rechts": False,
    "schalte dich auf rechts": False,
    "schalte dich auf rechts um": False,
    "schalte in die rechts position": False,
    "schalte in die rechte position": False,
    "schalte auf rechts": False,
    "schalte auf rechts um": False,
    "setze auf rechts": False,
    "stelle auf rechts": False,
    "aktiviere rechte position": False,
    "wähle rechts aus": False,
    "lege auf rechts": False,
    "lege auf rechts um": False,
    "ändere auf rechts": False,

    "links": True,
    "schalte links": True,
    "schalte dich links": True,
    "schalte dich auf links": True,
    "schalte dich auf links um": True,
    "schalte in die links position": True,
    "schalte in die linke position": True,
    "schalte auf links": True,
    "schalte auf links um": True,
    "setze auf links": True,
    "stelle auf links": True,
    "aktiviere linke position": True,
    "wähle links aus": True,
    "lege auf links": True,
    "lege auf links um": True,
    "ändere auf links": True,
}

accessories_left_turnouts_commands = {
    "rechts": True,
    "schalte rechts": True,
    "schalte dich rechts": True,
    "schalte dich auf rechts": True,
    "schalte dich auf rechts um": True,
    "schalte in die rechts position": True,
    "schalte in die rechte position": True,
    "schalte auf rechts": True,
    "schalte auf rechts um": True,
    "setze auf rechts": True,
    "stelle auf rechts": True,
    "aktiviere rechte position": True,
    "wähle rechts aus": True,
    "lege auf rechts": True,
    "lege auf rechts um": True,
    "ändere auf rechts": True,

    "links": False,
    "schalte links": False,
    "schalte dich links": False,
    "schalte dich auf links": False,
    "schalte dich auf links um": False,
    "schalte in die links position": False,
    "schalte in die linke position": False,
    "schalte auf links": False,
    "schalte auf links um": False,
    "setze auf links": False,
    "stelle auf links": False,
    "aktiviere linke position": False,
    "wähle links aus": False,
    "lege auf links": False,
    "lege auf links um": False,
    "ändere auf links": False,
}

accessories_triple_switch_commands = {
    #Dreiwegweichen
    #"links"
    #"mitte"
    #"rechts"
}

accessories_uncoupling_tracks_commands = {
    "aktivier": True,
    "aktiviere": True,
    "aktivieren": True,
    "aktiviert": True,
    "schalte ein": True,
    "schalte dich ein": True,
    "schalte an": True,
    "schalte dich an": True,
    "gehe an": True,
    "schalte auf": True,
    "entkuppeln": True,
    "entkupple": True,
    "abkuppeln": True,
    "entkupple dich": True,
    "löse Verbindung": True,
    "löse die Verbindung": True,
    "löse die Kupplung": True,
    "löse die Verbindung zwischen Wagen": True,
    "trenne Wagen": True,
    "trenne die Wagen": True,
    "löse die Wagen": True,
    "löse den Zug": True,
    "löse den Zugteil": True,
    "löse die Lokomotive": True,
    "kuppel ab": True,
    "kuppel die Wagen ab": True,
    "kuppel die Lokomotive ab": True,
    "kuppel den Zugteil ab": True,
    "kuppel den Zug ab": True,
    "kuppel dich ab": True,
    "kuppel die Kupplung ab": True,
    "trenne die Kupplung": True,
    "löse die Verbindung zwischen Lokomotive und Wagen": True,
}