train_speed_commands = {
    "stop": 0,
    "halt": 0,
    "halte an": 0,
    "anhalten": 0,
    "bleib stehen": 0,
    "start": 500,
    "beginne": 500,
    "starte": 500,
    "fahre": 500,
    "fahre los": 500,
    "losfahren": 500,
    "fahre so schnell wie möglich": 1000,
    "fahre mit voller geschwindigkeit": 1000,
    "maximale beschleunigung": 1000,
    "maximale geschwindigkeit": 1000,
}

increaseTrainSpeed = 200
reduceTrainSpeed = -200
train_add_speed_commands = {
    "schneller": increaseTrainSpeed,
    "fahre schneller": increaseTrainSpeed,
    "laufe schneller": increaseTrainSpeed,
    "bewege dich schneller": increaseTrainSpeed,
    "geschwindigkeit erhöhe": increaseTrainSpeed,
    "schneller fahren": increaseTrainSpeed,
    "schneller bewegen": increaseTrainSpeed,
    "schneller voran": increaseTrainSpeed,
    "schneller nach vorne": increaseTrainSpeed,
    "erhöhe geschwindigkeit": increaseTrainSpeed,
    "beschleunige": increaseTrainSpeed,
    "tempo erhöhen": increaseTrainSpeed,
    "erhöhe tempo": increaseTrainSpeed,

    "langsamer": reduceTrainSpeed,
    "fahre langsamer": reduceTrainSpeed,
    "laufe langsamer": reduceTrainSpeed,
    "bewege dich langsamer": reduceTrainSpeed,
    "geschwindigkeit verringere": reduceTrainSpeed,
    "langsamer fahren": reduceTrainSpeed,
    "langsamer bewegen": reduceTrainSpeed,
    "langsamer voran": reduceTrainSpeed,
    "langsamer nach vorne": reduceTrainSpeed,
    "verringere geschwindigkeit": reduceTrainSpeed,
    "verlangsamen": reduceTrainSpeed,
    "tempo verringern": reduceTrainSpeed,
    "verringere tempo": reduceTrainSpeed,
}

train_direction_commands = {
    #Commands for train direction with speed stop

    #Direction forwards
    "geradeaus": "Forwards",
    "schalte geradeaus": "Forwards",
    "schalte in richtung geradeaus": "Forwards",
    "schalte in die richtung geradeaus": "Forwards",

    "setze den weg geradeaus": "Forwards",
    "setze den pfad geradeaus": "Forwards",
    "setze den kurs geradeaus": "Forwards",
    "setze die route geradeaus": "Forwards",
    "setze die richtung geradeaus": "Forwards",

    "vorwärts": "Forwards",
    "schalte vorwärts": "Forwards",
    "schalte in richtung vorwärts": "Forwards",
    "schalte in die richtung vorwärts": "Forwards",

    "setze den weg auf vorwärts": "Forwards",
    "setze den pfad auf vorwärts": "Forwards",
    "setze den kurs auf vorwärts": "Forwards",
    "setze die route auf vorwärts": "Forwards",
    "setze die richtung auf vorwärts": "Forwards",

    #Direction backwards
    "rückwärts": "Backwards",
    "schalte rückwärts": "Backwards",
    "schalte in richtung rückwärts": "Backwards",
    "schalte in die richtung rückwärts": "Backwards",

    "setze den weg rückwärts": "Backwards",
    "setze den pfad rückwärts": "Backwards",
    "setze den kurs rückwärts": "Backwards",
    "setze die route rückwärts": "Backwards",
    "setze die richtung rückwärts": "Backwards",

    "nach hinten": "Backwards",
    "schalte nach hinten": "Backwards",
    "schalte in richtung nach hinten": "Backwards",
    "schalte in die richtung nach hinten": "Backwards",

    "setze den weg auf nach hinten": "Backwards",
    "setze den pfad auf nach hinten": "Backwards",
    "setze den kurs auf nach hinten": "Backwards",
    "setze die route auf nach hinten": "Backwards",
    "setze die richtung auf nach hinten": "Backwards",
}

train_direction_speed_commands = {
    #Commands for train direction with speed continue

    #Direction forwards
    "fahre rückwärts": "Forwards",
    "fahre in richtung rückwärts": "Forwards",
    "fahre in die richtung rückwärts": "Forwards",
    "fahre weiter rückwärts": "Forwards",
    "fahre weiter in richtung rückwärts": "Forwards",
    "fahre weiter in die richtung rückwärts": "Forwards",
    "fahre mit selber geschwindigkeit rückwärts": "Forwards",
    "fahre mit gleicher geschwindigkeit rückwärts": "Forwards",
    "fahre mit gleicher geschwindigkeit in richtung rückwärts": "Forwards",
    "fahre mit gleicher geschwindigkeit in die richtung rückwärts": "Forwards",
    "fahre mit der selber geschwindigkeit rückwärts": "Forwards",
    "fahre mit der gleicher geschwindigkeit rückwärts": "Forwards",
    "fahre mit der gleicher geschwindigkeit in richtung rückwärts": "Forwards",
    "fahre mit der gleicher geschwindigkeit in die richtung rückwärts": "Forwards",
    "in richtung rückwärts fahren": "Forwards",
    "in richtung rückwärts bewegen": "Forwards",
    "gleiche geschwindigkeit rückwärts": "Forwards",
    "gleiche geschwindigkeit in richtung rückwärts": "Forwards",
    "gleiche geschwindigkeit in die richtung rückwärts": "Forwards",
    "mit gleicher geschwindigkeit rückwärts": "Forwards",
    "mit gleicher geschwindigkeit in richtung rückwärts": "Forwards",
    "mit gleicher geschwindigkeit in die richtung rückwärts": "Forwards",
    "mit der gleicher geschwindigkeit rückwärts": "Forwards",
    "mit der gleicher geschwindigkeit in richtung rückwärts": "Forwards",
    "mit der gleicher geschwindigkeit in die richtung rückwärts": "Forwards",

    "fahre nach hinten": "Forwards",
    "fahre in richtung nach hinten": "Forwards",
    "fahre in die richtung nach hinten": "Forwards",
    "fahre weiter nach hinten": "Forwards",
    "fahre weiter in richtung nach hinten": "Forwards",
    "fahre weiter in die richtung nach hinten": "Forwards",
    "fahre mit selber geschwindigkeit nach hinten": "Forwards",
    "fahre mit gleicher geschwindigkeit nach hinten": "Forwards",
    "fahre mit gleicher geschwindigkeit in richtung nach hinten": "Forwards",
    "fahre mit gleicher geschwindigkeit in die richtung nach hinten": "Forwards",
    "fahre mit der selber geschwindigkeit nach hinten": "Forwards",
    "fahre mit der gleicher geschwindigkeit nach hinten": "Forwards",
    "fahre mit der gleicher geschwindigkeit in richtung nach hinten": "Forwards",
    "fahre mit der gleicher geschwindigkeit in die richtung nach hinten": "Forwards",
    "in richtung nach hinten fahren": "Forwards",
    "in richtung nach hinten bewegen": "Forwards",
    "gleiche geschwindigkeit nach hinten": "Forwards",
    "gleiche geschwindigkeit in richtung nach hinten": "Forwards",
    "gleiche geschwindigkeit in die richtung nach hinten": "Forwards",
    "mit gleicher geschwindigkeit nach hinten": "Forwards",
    "mit gleicher geschwindigkeit in richtung nach hinten": "Forwards",
    "mit gleicher geschwindigkeit in die richtung nach hinten": "Forwards",
    "mit der gleicher geschwindigkeit nach hinten": "Forwards",
    "mit der gleicher geschwindigkeit in richtung nach hinten": "Forwards",
    "mit der gleicher geschwindigkeit in die richtung nach hinten": "Forwards",

    "gerade nach vorne": "Forwards",
    "voran": "Forwards",
    "nach vorn": "Forwards",
    "nach vorn bewegen": "Forwards",
    "bewege dich nach vorn": "Forwards",
    "bewege dich voran": "Forwards",
    "gehe voran": "Forwards",
    "fahre weiter voran": "Forwards",
    "fahre nach vorne": "Forwards",

    #Direction backwards
    "fahre geradeaus": "Backwards",
    "fahre in richtung geradeaus": "Backwards",
    "fahre in die richtung geradeaus": "Backwards",
    "fahre weiter geradeaus": "Backwards",
    "fahre weiter in richtung geradeaus": "Backwards",
    "fahre weiter in die richtung geradeaus": "Backwards",
    "fahre mit selber geschwindigkeit geradeaus": "Backwards",
    "fahre mit gleicher geschwindigkeit geradeaus": "Backwards",
    "fahre mit gleicher geschwindigkeit in richtung geradeaus": "Backwards",
    "fahre mit gleicher geschwindigkeit in die richtung geradeaus": "Backwards",
    "fahre mit der selber geschwindigkeit geradeaus": "Backwards",
    "fahre mit der gleicher geschwindigkeit geradeaus": "Backwards",
    "fahre mit der gleicher geschwindigkeit in richtung geradeaus": "Backwards",
    "fahre mit der gleicher geschwindigkeit in die richtung geradeaus": "Backwards",
    "in richtung geradeaus fahren": "Backwards",
    "in richtung geradeaus bewegen": "Backwards",
    "gleiche geschwindigkeit geradeaus": "Backwards",
    "gleiche geschwindigkeit in richtung geradeaus": "Backwards",
    "gleiche geschwindigkeit in die richtung geradeaus": "Backwards",
    "mit gleicher geschwindigkeit geradeaus": "Backwards",
    "mit gleicher geschwindigkeit in richtung geradeaus": "Backwards",
    "mit gleicher geschwindigkeit in die richtung geradeaus": "Backwards",
    "mit der gleicher geschwindigkeit geradeaus": "Backwards",
    "mit der gleicher geschwindigkeit in richtung geradeaus": "Backwards",
    "mit der gleicher geschwindigkeit in die richtung geradeaus": "Backwards",

    "fahre vorwärts": "Backwards",
    "fahre in richtung vorwärts": "Backwards",
    "fahre in die richtung vorwärts": "Backwards",
    "fahre weiter vorwärts": "Backwards",
    "fahre weiter in richtung vorwärts": "Backwards",
    "fahre weiter in die richtung vorwärts": "Backwards",
    "fahre mit selber geschwindigkeit vorwärts": "Backwards",
    "fahre mit gleicher geschwindigkeit vorwärts": "Backwards",
    "fahre mit gleicher geschwindigkeit in richtung vorwärts": "Backwards",
    "fahre mit gleicher geschwindigkeit in die richtung vorwärts": "Backwards",
    "fahre mit der selber geschwindigkeit vorwärts": "Backwards",
    "fahre mit der gleicher geschwindigkeit vorwärts": "Backwards",
    "fahre mit der gleicher geschwindigkeit in richtung vorwärts": "Backwards",
    "fahre mit der gleicher geschwindigkeit in die richtung vorwärts": "Backwards",
    "in richtung vorwärts fahren": "Backwards",
    "in richtung vorwärts bewegen": "Backwards",
    "gleiche geschwindigkeit vorwärts": "Backwards",
    "gleiche geschwindigkeit in richtung vorwärts": "Backwards",
    "gleiche geschwindigkeit in die richtung vorwärts": "Backwards",
    "mit gleicher geschwindigkeit vorwärts": "Backwards",
    "mit gleicher geschwindigkeit in richtung vorwärts": "Backwards",
    "mit gleicher geschwindigkeit in die richtung vorwärts": "Backwards",
    "mit der gleicher geschwindigkeit vorwärts": "Backwards",
    "mit der gleicher geschwindigkeit in richtung vorwärts": "Backwards",
    "mit der gleicher geschwindigkeit in die richtung vorwärts": "Backwards",

    "gerade nach hinten": "Backwards",
    "nach hinten": "Backwards",
    "nach hinten bewegen": "Backwards",
    "bewege dich nach hinten": "Backwards",
    "bewege dich hinten": "Backwards",
    "gehe hinten": "Backwards",
    "fahre weiter hinten": "Backwards",
}